### ISSUE TITLE
traceback

### ISSUE THREAD

**Issue by diesel437** [oxplot/imdb2json#6]
doom@ar:~/imdb2json$ python3 imdb2json.py convert title ratings.list.gz actors.list.gz
    Traceback (most recent call last):
      File "imdb2json.py", line 887, in <module>
        main()
      File "imdb2json.py", line 848, in main
        args.fn(args)
      File "imdb2json.py", line 868, in do_convert
        )), key=lambda x: x[0]):
      File "imdb2json.py", line 165, in rec_sorted
        ) for f in temps), key=lambda x: x[0])
    TypeError: merge() got an unexpected keyword argument 'key'
    doom@ar:~/imdb2json$

**Comment by oxplot** [comment]
`key` parameter of `heapq.merge()` function [was added in Python 3.5](https://docs.python.org/3/library/heapq.html#heapq.merge).

**Comment by oxplot** [comment]
I just updated the readme with specific compatible python version.
